import turtle

colors = ['red', 'purple', 'blue', 'green', 'orange', 'yellow']
marker = turtle.Pen()

turtle.bgcolor('black')

for x in range(20):
    marker.speed(2000)
    marker.pencolor(colors[x%6])
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.speed(200)
    marker.pencolor(colors[x%6])
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)
    marker.width(x//100 + 1)
    marker.forward(x)
    marker.left(91)

turtle.done()
